/**
 * AI&D SOFI-META API
 * AI&D SOFI Meta Data Services API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ModelSAInfraIntegration } from './modelSAInfraIntegration';
import { ModelSAUXIntegration } from './modelSAUXIntegration';

export interface ModelSAUpdateData { 
    data: ModelSAInfraIntegration | ModelSAUXIntegration;
}