/**
 * AI&D SOFI-META API
 * AI&D SOFI Meta Data Services API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { DateTime } from "luxon";

export interface ModelSAUXIntegration { 
    createDatetime: DateTime; 
    createdBy: string;
    data: ModelSAUXIntegrationData;
    updateDatetime: DateTime;
    updatedBy: string;
    _id: string;
}

export interface ModelSAUXIntegrationData {
    ux_link_home: string;
    ux_link_verify_email: string;
    ux_link_reset_pw: string;
    type: string;
}

// export interface ModelSAInfraIntegrationUpdate {
//     data: ModelSAUXIntegrationData;
// }
