/**
 * AI&D SOFI-META API
 * AI&D SOFI Meta Data Services API
 *
 * OpenAPI spec version: 0.0.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { OnlineStatus } from './onlineStatus';

export interface ModelUserUpdateStatus { 
    onlineStatus: OnlineStatus;
}