export * from './auth.service';
import { AuthService } from './auth.service';
export * from './contentCategory.service';
import { ContentCategoryService } from './contentCategory.service';
export * from './default.service';
import { DefaultService } from './default.service';
import { SharedService } from './shared.service';
export * from './superAdmin.service';
import { SuperAdminService } from './superAdmin.service';
export * from './shared.service';
import { UserService } from './user.service';
export * from './user.service';
export const APIS = [AuthService, DefaultService, SuperAdminService, UserService, ContentCategoryService,SharedService];
