export * from './auth.service';
import { AuthService } from './auth.service';
export * from './contentCategory.service';
import { ContentCategoryService } from './contentCategory.service';
export * from './default.service';
import { DefaultService } from './default.service';
export * from './superAdmin.service';
import { SuperAdminService } from './superAdmin.service';
export * from './user.service';
import { UserService } from './user.service';
export const APIS = [AuthService, ContentCategoryService, DefaultService, SuperAdminService, UserService, ContentCategoryService];
